const bad=['ÃƒÂ¤Ã‚Â¸ÃƒÂ§Ã‚Â½ÃƒÂ‘','ÃƒÂ¥Ã‚Â¤ÃƒÂœÃƒÂ¦Ã‚Â˜ÃƒÂŸ','縺薙ｓ縺ｫ縺｡縺ｯ','â€žâ˜†Ã‚Â¤'];
const game={id:Number(localStorage.getItem('visitor_id')||1337),progress:Number(localStorage.getItem('progress')||0),clues:JSON.parse(localStorage.getItem('discovered_clues')||'[]')};
function saveGame(){localStorage.setItem('visitor_id',game.id);localStorage.setItem('progress',game.progress);localStorage.setItem('discovered_clues',JSON.stringify(game.clues));}
function solve(chapter,clue){game.progress=Math.max(game.progress,chapter);if(!game.clues.includes(clue))game.clues.push(clue);saveGame();}
function padded(n){return String(n).padStart(7,'0')}
function toggleMidi(){const s=document.getElementById('midi-status');if(s)s.textContent=s.textContent.includes('stopped')?'[ playing... ] my_song.mid ♪':'[ stopped ] my_song.mid'}
function signGuestbook(){const n=(document.getElementById('guest-name').value||'anonymous').replace(/[<>]/g,'');const m=(document.getElementById('guest-msg').value||bad[Math.floor(Math.random()*bad.length)]).replace(/[<>]/g,'');document.getElementById('guest-log').innerHTML+='<br>'+n+': '+m;solve(1,'guestbook')}
function initHomepage(){const counter=document.getElementById('counter');if(!counter)return;const note=document.getElementById('counter-note');counter.textContent=padded(game.id);if(game.progress>=7){document.getElementById('guest-log').innerHTML+='<br><i>Eli: 你别怕。</i>'}if(game.progress>=10){note.textContent=' 他在等你。'}if(new URLSearchParams(location.search).get('debug')==='1'){const d=document.createElement('pre');d.className='tiny';d.textContent='ARG_INTERNAL\nchapter='+game.progress+'\nvisitor='+game.id+'\nclues='+game.clues.join(',');document.querySelector('.footer').appendChild(d)}}
function recordVisit(name){const seen=JSON.parse(sessionStorage.getItem('visited_pages')||'[]');if(!seen.includes(name)){seen.push(name);sessionStorage.setItem('visited_pages',JSON.stringify(seen));}return seen}
document.addEventListener('mousemove',e=>{if(Math.random()>.92){const p=document.createElement('span');p.className='particle';p.textContent=bad[Math.floor(Math.random()*bad.length)];p.style.left=e.clientX+'px';p.style.top=e.clientY+'px';document.getElementById('glitches')?.appendChild(p);setTimeout(()=>p.remove(),1100)}});
