const bad = ['ÃƒÂ¤Ã‚Â¸ÃƒÂ§Ã‚Â½ÃƒÂ‘', 'ÃƒÂ¥Ã‚Â¤ÃƒÂœÃƒÂ¦Ã‚Â˜ÃƒÂŸ', '縺薙ｓ縺ｫ縺｡縺ｯ', 'â€žâ˜†Ã‚Â¤', 'ÐšÐ¾Ð¼Ð½Ð°Ñ‚Ð°', '0x09 0x17 0x20 0x01', 'ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦'];
const state = { visits: Number(localStorage.getItem('a_visits') || 1337) };
const app = document.getElementById('app');
function padded(n) { return String(n).padStart(7, '0'); }
function setTitle(text) { let i = 0; clearInterval(window.titleTimer); window.titleTimer = setInterval(() => { document.title = text.slice(i) + ' /// ' + text.slice(0, i); i = (i + 1) % text.length; }, 260); }
function makeRoom() { const c = document.createElement('canvas'); c.width=380; c.height=156; const x=c.getContext('2d'); x.fillStyle='#21134a';x.fillRect(0,0,380,156);x.fillStyle='#101018';x.fillRect(0,105,380,51);x.fillStyle='#ffdf71';x.fillRect(25,25,105,55);x.fillStyle='#5c3822';x.fillRect(0,80,380,10);x.fillStyle='#222';x.fillRect(166,58,135,48);x.fillStyle='#00c6c6';x.fillRect(175,65,117,33);x.fillStyle='#d33';x.fillRect(310,19,45,60);x.fillStyle='#fff';x.fillRect(316,26,33,8);x.fillStyle='#f44';x.fillRect(315,43,31,5);x.fillStyle='#aaa';x.fillRect(70,116,25,6);x.fillStyle='#f00';x.fillRect(202,110,26,5);x.fillStyle='#0ff';x.fillRect(240,114,52,4);x.fillStyle='#fff';x.font='9px monospace';x.fillText("A'S ROOM 2001",180,83); document.getElementById('room-image').src=c.toDataURL('image/gif'); }
function toggleMidi() { const s=document.getElementById('midi-status'); s.textContent=s.textContent.includes('stopped')?'[ playing... ] dreaming.mid ♪♪':'[ stopped ] dreaming.mid'; }
function signGuestbook() { const n=(document.getElementById('guest-name').value||'anonymous').replace(/[<>]/g,''); const m=(document.getElementById('guest-msg').value||bad[Math.floor(Math.random()*bad.length)]).replace(/[<>]/g,''); document.getElementById('guest-log').innerHTML += '<br>'+n+': '+m; }
function initHomepage() { const counter=document.getElementById('counter'); if (!counter) return; let seen=Number(sessionStorage.getItem('archive_home_opens')||0); if (!sessionStorage.getItem('archive_home_seen')) { sessionStorage.setItem('archive_home_seen','1'); state.visits=1337; } else if (seen < 3) { state.visits=1338+seen; } sessionStorage.setItem('archive_home_opens',String(seen+1)); localStorage.setItem('a_visits',state.visits); counter.textContent=padded(state.visits); const log=document.getElementById('guest-log'),links=document.getElementById('links'); if(state.visits>=1340){ log.innerHTML+='<br><span class="blink">A [2026.09.17 23:41:07]: you shouldn\'t be here</span>'; links.insertAdjacentHTML('beforeend','<br><a href="archive/">[ archive status ]</a>'); } if(state.visits>=1341) document.getElementById('counter-note').textContent=' HELLO, 1341.'; }
function roomClue() { const note=document.getElementById('counter-note'); if(note) note.textContent='  [the monitor is still on]'; document.body.classList.add('shake'); setTimeout(()=>document.body.classList.remove('shake'),250); }
function crc32(bytes) { let c=0xffffffff; for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);} return (c^0xffffffff)>>>0; }
function downloadRoom(e) { e.preventDefault(); const enc=new TextEncoder(), files=[['readme.txt','IF YOU FOUND THIS,\nYOU ARE ALREADY TOO LATE.\n\nDON\'T OPEN 2007.TXT'],['2007.txt','2007\nI thought deleting the page would fix it.\nIt didn\'t.\n\nEvery time I delete something,\nsomething else appears.\n\nYesterday I found a page dated\n09/17/2001\nthat I never created.\n\n— A']]; const gif=atob('R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs='), gifBytes=Uint8Array.from(gif,c=>c.charCodeAt(0)); let zip=[],offset=gifBytes.length; for(const [name,text] of files){const n=enc.encode(name),d=enc.encode(text),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint32(14,crc32(d),true);v.setUint32(18,d.length,true);v.setUint32(22,d.length,true);v.setUint16(26,n.length,true);h.set(n,30);zip.push(h,d);offset+=h.length+d.length;} const central=[];let localOffset=gifBytes.length;for(const [name,text] of files){const n=enc.encode(name),d=enc.encode(text),h=new Uint8Array(46+n.length),v=new DataView(h.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(8,20,true);v.setUint32(16,crc32(d),true);v.setUint32(20,d.length,true);v.setUint32(24,d.length,true);v.setUint16(28,n.length,true);v.setUint32(42,localOffset,true);h.set(n,46);central.push(h);localOffset+=30+n.length+d.length;} const cd=central.reduce((a,b)=>a+b.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,cd,true);ev.setUint32(16,offset,true);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([gifBytes,...zip,...central,end],{type:'image/gif'}));a.download='room_final_FINAL2.gif';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);roomClue(); }
document.addEventListener('mousemove',e=>{if(Math.random()>.86){const p=document.createElement('span');p.className='particle';p.textContent=bad[Math.floor(Math.random()*bad.length)];p.style.left=e.clientX+'px';p.style.top=e.clientY+'px';document.getElementById('glitches').appendChild(p);setTimeout(()=>p.remove(),1200);}});
window.addEventListener('storage',()=>{state.visits++;localStorage.setItem('a_visits',state.visits);});
setInterval(()=>{if(Math.random()>.78){document.body.classList.add('shake');setTimeout(()=>document.body.classList.remove('shake'),250);}},7000);
